version: '3.8'

services:
  gymcrm-main:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=local
      - EUREKA_CLIENT_ENABLED=false
      - SPRING_ACTIVEMQ_BROKER_URL=disabled
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  gymcrm-report:
    build:
      context: .
      dockerfile: Dockerfile.report
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=local
      - EUREKA_CLIENT_ENABLED=false
      - SPRING_ACTIVEMQ_BROKER_URL=disabled
      - SERVER_PORT=8081
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3